"""empty message

Revision ID: e1db35517f1a
Revises: 355c5f5d887c
Create Date: 2022-06-05 01:11:50.325706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1db35517f1a'
down_revision = '355c5f5d887c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('date_added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'date_added')
    # ### end Alembic commands ###
